# -*- coding: utf-8 -*-
"""bolunmekural.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pftNvu3theZgx4FuI0TMXNT0QZjthlRD
"""

for sayi in range(1, 101):
 print(sayi, "sayısı:")
 if sayi%2==0:
  print("2 ile tam bölünür.")
 if sayi%3==0:
  print("3 ile tam bölünür.")
 if sayi%4==0:
  print("4 ile tam bölünür.")
 if sayi%5==0:
  print("5 ile tam bölünür.")
 if sayi%6==0:
  print("6 ile tam bölünür.")
 if sayi%8==0:
  print("8 ile tam bölünür.")
 if sayi%9==0:
  print("9 ile tam bölünür.")
 if sayi%10==0:
  print("10 ile tam bölünür.")
 if sayi%12==0:
  print("12 ile tam bölünür.")